version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: zabbix_db
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - zabbix_db_data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix_server
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    ports:
      - "10051:10051"
    depends_on:
      - db
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix_web
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    volumes:
      - zabbix_web_data:/etc/zabbix/web
    ports:
      - "8080:8080"
    depends_on:
      - db
      - zabbix-server
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.0-latest
    container_name: zabbix_agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    volumes:
      - zabbix_agent_data:/var/lib/zabbix
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

volumes:
  zabbix_db_data:
  zabbix_server_data:
  zabbix_web_data:
  zabbix_agent_data:

networks:
  zabbix-network:
    driver: bridge
